### PR TITLE
Register warden jakn00

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden jakn00

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Comment by jakn00** [comment]
Hey, I've just verified my email and changed my user name in Discord.

**Comment by SamusElderg** [comment]
> Hey, I've just verified my email and changed my user name in Discord.

Thanks, we will also need you to check into the `i-want-to-be-a-warden` channel in the Code4rena Discord channel and mention this PR (`jakn00 `)

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
