### PR TITLE
Add warden Ozodbek

### PR DESCRIPTION
**Pull request by code423n4**
This auto-generated PR registers the new warden Ozodbek

### CODE REVIEW

**Comment by CloudEllie** [comment]
@kartoonjoy looks like this one got a 👎 so I think we can close it - but will defer to you.

**Comment by CloudEllie** [comment]
Oops, sorry - seeing now they registered pre-form change. :)

**Comment by itsmetechjay** [comment]
Applying `hold` label here so we know it's in progress.

**Comment by kartoonjoy** [comment]
Closing the request as no response has been received from the warden. Thanks

**Pull request closed without merging**
