### PR TITLE
Register warden jakku

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden jakku

@shajipapn

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by shajipapn** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

jakku#2458

**Comment by SamusElderg** [comment]
> > Can not find a matching user in Discord, will leave the application open for now though
> 
> jakku#2458

Thanks for the clarification! You do not appear to be a member of the Code4rena Discord channel yet though, can i please ask that you join the channel and check into the `i-want-to-be-a-warden` channel?

**Comment by shajipapn** [comment]
> > > Can not find a matching user in Discord, will leave the application open for now though
> > 
> > 
> > jakku#2458
> 
> Thanks for the clarification! You do not appear to be a member of the Code4rena Discord channel yet though, can i please ask that you join the channel and check into the `i-want-to-be-a-warden` channel?

Hi, Joined now. Please check

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel, closing this PR for now, can re-open when/if checked in

**Pull request closed without merging**
