### PR TITLE
Register warden mazi_xyz

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden mazi_xyz

@E-Zbox

### CODE REVIEW

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by E-Zbox** [comment]
Hello Samus,
What nickname should I change?

**Comment by sksb2180** [comment]
> Hello Samus, What nickname should I change?

With which you registered on code4rena website.

**Comment by SamusElderg** [comment]
> Hello Samus, What nickname should I change?

Check Discord please! I made an assumption about which Discord user is yours but pretty confident its the right one. My message was: "Looks like you might have chosen username: `mazi_xyz`. If this is correct, can you please set your local nickname in this Discord server (not your global Discord handle) to match that exactly, then ping me afterwards. You can do so by manually typing in the `/nick` command and then paste in this as your new nickname: `mazi_xyz`"

**Comment by E-Zbox** [comment]
> > Hello Samus, What nickname should I change?
> 
> Check Discord please! I made an assumption about which Discord user is yours but pretty confident its the right one. My message was:
> 
> "Looks like you might have chosen username: `mazi_xyz`. If this is correct, can you please set your local nickname in this Discord server (not your global Discord handle) to match that exactly, then ping me afterwards. You can do so by manually typing in the `/nick` command and then paste in this as your new nickname: `mazi_xyz`"

I've successfully changed my nick to `mazi_xyz`

**Comment by E-Zbox** [comment]
Hello,
It's E-Zbox from GitHub, I've successfully changed my Discord nick on
server to *mazi_xyz*

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
