### PR TITLE
Register warden notyeteth

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden notyeteth

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Comment by achrafezo** [comment]
user discord = asmitk#0353

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by achrafezo** [comment]
Hi I hqve changed the user name to notyeteth#0353

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
