### PR TITLE
Register warden y51r

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden y51r

@Irys17

### CODE REVIEW

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by Irys17** [comment]
> Have contacted user to change their nickname to match application

What should I do toi change nikename ?

**Review by Irys17 — APPROVED** [review]

**Review by Irys17 — APPROVED** [review]

**Comment by SamusElderg** [comment]
> > Have contacted user to change their nickname to match application
> 
> What should I do toi change nikename ?

Check the reply on discord here: https://discord.com/channels/810916927919620096/810957404887973929/1115991472701968424

**Comment by SamusElderg** [comment]
Closing PR for now, will re-open once nickname is matching application

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
