### PR TITLE
Register warden ironside

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden ironside

@igorroncevic

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by sksb2180** [comment]
Closed due to inactive after 2 days.

**Comment by igorroncevic** [comment]
May the application be reopened? I wasn't aware that I needed to provide this data during the weekend.
Discord username is ironside7

**Comment by igorroncevic** [comment]
May the application be reopened? I wasn't aware that I needed to provide this data during the weekend.
Discord username is ironside7

@sksb2180 @SamusElderg

**Comment by SamusElderg** [comment]
> May the application be reopened? I wasn't aware that I needed to provide this data during the weekend. Discord username is ironside7
> 
> @sksb2180 @SamusElderg

There is no rush dont worry, just standard practice closing PRs after 48hrs to keep things clean in here, we can re-open it any time! Will do once you check into the `i-want-to-be-a-warden` channel. Make sure you mention this PR `ironside` to make it easier for the contributors to corss-ref it too! Thanks

**Comment by igorroncevic** [comment]
> > May the application be reopened? I wasn't aware that I needed to provide this data during the weekend. Discord username is ironside7
> > @sksb2180 @SamusElderg
> 
> There is no rush dont worry, just standard practice closing PRs after 48hrs to keep things clean in here, we can re-open it any time! Will do once you check into the `i-want-to-be-a-warden` channel. Make sure you mention this PR `ironside` to make it easier for the contributors to corss-ref it too! Thanks

Did that 🙌

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
