### PR TITLE
Register warden arch0125

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden arch0125

@Arch0125

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by Arch0125** [comment]
@SamusElderg @sksb2180 Hey can you check now ive joined the discord server

**Comment by SamusElderg** [comment]
> @SamusElderg @sksb2180 Hey can you check now ive joined the discord server

Hi 👋 what is your Discord handle/username? Thanks

**Comment by Arch0125** [comment]
@SamusElderg Archisman Das #9013

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
