### PR TITLE
Register warden jnforja

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden jnforja

@jnforja

### CODE REVIEW

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden`yet.

**Comment by Jnforja** [comment]
Hey, already checked i-want-to-be-a-warden channel.

**Comment by sksb2180** [comment]
> Hey, already checked i-want-to-be-a-warden channel.

I pinged you to change your nickname to jnforja already.

**Comment by Jnforja** [comment]
> > Hey, already checked i-want-to-be-a-warden channel.
> 
> I pinged you to change your nickname to jnforja already. 
> 

Thanks for the heads up. Changed my display name on discord to jnforja.

**Comment by sksb2180** [comment]
> > > Hey, already checked i-want-to-be-a-warden channel.
> > 
> > 
> > I pinged you to change your nickname to jnforja already.
> 
> Thanks for the heads up. Changed my display name on discord to jnforja.

Please reply again in the channel `i-want-to-be-a-warden`. thank you

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
