### PR TITLE
Register warden 0xPastaman

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden 0xPastaman

@SebMelendez01

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by SebMelendez01** [comment]
> Can not find a matching user in Discord, will leave the application open for now though
Did I enter the wrong discord username? it should be 0xpastman, I was originally know as pastaman123#9998

**Comment by sksb2180** [comment]
Closed due to inactive after 2 days.

**Comment by SamusElderg** [comment]
> > Can not find a matching user in Discord, will leave the application open for now though
> 
> Did I enter the wrong discord username? it should be 0xpastman, I was originally know as pastaman123#9998

Thanks! Just need you to check into the `i-want-to-be-a-warden` channel in the C4 discord and mention this PR (`0xPastaman`) and we will be able to direct you and re-open this 🙏

**Pull request closed without merging**
