### PR TITLE
Register warden anodaram

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden anodaram

### CODE REVIEW

**Review by anodaram — APPROVED** [review]
reviewed

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by anodaram** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

ChainDev#1617
This is my Discord

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by anodaram** [comment]
> Have contacted user ChainDev#1617 to change their nickname to match application

Sure, changed it

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
