### PR TITLE
Add warden 8olidity

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden 8olidity

my blog:
https://8olidity.gitbook.io/

### CODE REVIEW

**Comment by SamusElderg** [comment]
Have emailed the user at the email address listed in their gitbook to provide direction on what they need to do to proceed

**Comment by onuhr** [comment]
The user just texted on the #i-want-an-audit channel. Looks like a sponsor?

**Comment by itsmetechjay** [comment]
The user submitted a help desk request. I encouraged them to check their email and provide the additional information needed to process the registration.

**Comment by SamusElderg** [comment]
I am in a PM with the user now to confirm additional details

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
