### PR TITLE
Register warden XdpCs

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden XdpCs

@XdpCs

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by XdpCs** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

1015229701716975616 is my discord's user ID

**Comment by XdpCs** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

I already joined the server.

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Comment by XdpCs** [comment]
> Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

@sksb2180 I chat in `i-want-to-be-a-warden ` now

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
