### PR TITLE
Register warden brendan

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden brendan

### CODE REVIEW

**Comment by SamusElderg** [comment]
Have PMed user, they are not checked into the channel yet

**Comment by SamusElderg** [comment]
This was a mason application, I'm going to merge it without adding warden title, i think that's correct?

**Comment by SamusElderg** [comment]
> This was a mason application, I'm going to merge it without adding warden title, i think that's correct?

Awaiting advice before we action this one

**Comment by SamusElderg** [comment]
Closing this PR for now, the applicant was only applying to become a mason, not a warden

**Comment by kartoonjoy** [comment]
Closing this as it was completed in error.

**Pull request closed without merging**
