### PR TITLE
Register warden Maher

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Maher

@MaherAzzouzi

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by MaherAzzouzi** [comment]
My Discord is MA#3496

**Comment by SamusElderg** [comment]
> My Discord is MA#3496

No users in the code4rena discord with that handle? Can you please make sure your handle matches what you put in the application (probably `MA#3496` as you say, i have no way to confirm this) and also that your *nickname* (not global handle) in the Code4rena Discord server matches your chosen C4 username: `Maher` and also make sure you check into the `i-want-to-be-a-warden` channel in the Code4rena discord server, Thanks!

**Comment by SamusElderg** [comment]
Closing PR for now, if user checks in with matching nickname<>username will reopen

**Pull request closed without merging**
