### PR TITLE
Register warden dinesh

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden dinesh

### CODE REVIEW

**Review by aravindb26 — COMMENTED** [review]
Howl

**Comment by aravindb26** [comment]
Hi

**Review by aravindb26 — CHANGES_REQUESTED** [review]
Approve

**Review by aravindb26 — CHANGES_REQUESTED** [review]
Done

**Review by aravindb26 — APPROVED** [review]
Hello

**Review by kartoonjoy — APPROVED** [review]

**Review by aravindb26 — COMMENTED** [review]
thank you

**Pull request merged**
