### PR TITLE
Register warden unkn0wn

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden unkn0wn

### CODE REVIEW

**Review by unkn-0wn — APPROVED** [review]

**Review by unkn-0wn — APPROVED** [review]
This seems perfect.

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel

**Review by unkn-0wn — COMMENTED** [review]
Hey. I didn't know I needed to do that.
I already joined the discord channel and interacted in the `#i-want-to-be-a-warden` with the same display name.

**Comment by sksb2180** [comment]
Closed due to inactive after 2 days.

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by unkn-0wn** [comment]
Hey, I have made the necessary changes.

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
