### PR TITLE
Include me to leaderboard

### PR DESCRIPTION
**Pull request by alexon1234**

### CODE REVIEW

**Comment by adamavenir** [comment]
@dstaley can you help me out and investigate why @alexon1234 didn't show up on the leaderboard after this pr? I do see them listed with results in `_data/findings/findings.json` but I haven't looked deeper than that.

**Comment by dstaley** [comment]
> @dstaley can you help me out and investigate why @alexon1234 didn't show up on the leaderboard after this pr? I do see them listed with results in `_data/findings/findings.json` but I haven't looked deeper than that.

This PR adds the handle to the `data/handles` directory, when it needs to be in the `_data/handles` directory.

@alexon1234 Sorry about the confusion!

**Comment by ninek9** [comment]
I wondered if it was possible they didn’t show up due to 0 reward
balance but I didn’t have a way to check. Was gonna raise it in the
morning. :)

On May 17, 2021, GitHub ***@***.***> wrote:
> > @dstaley <https://github.com/dstaley> can you help me out and
> > investigate why @alexon1234 <https://github.com/alexon1234> didn't
> > show up on the leaderboard after this pr? I do see them listed with
> > results in _data/findings/findings.json but I haven't looked deeper
> > than that.
> >
>
> This PR adds the handle to the data/handles directory, when it needs
> to be in the _data/handles directory.
>
> @alexon1234 <https://github.com/alexon1234> Sorry about the confusion!
>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/code-423n4/code423n4.com/pull/33#issuecomment-
842794277>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAETDCQPG2CNSL2V4THJJ4LTOHL4HANCNFSM4454QNHA>.

**Comment by alexon1234** [comment]
> 
> 
> > @dstaley can you help me out and investigate why @alexon1234 didn't show up on the leaderboard after this pr? I do see them listed with results in `_data/findings/findings.json` but I haven't looked deeper than that.
> 
> This PR adds the handle to the `data/handles` directory, when it needs to be in the `_data/handles` directory.
> 
> @alexon1234 Sorry about the confusion!

If it should be added inside `_data`, we should update the README.md because in there it says 
_1. Add a JSON file for yourself at data/handles:_

**Pull request merged**
