### PR TITLE
Register warden AmariS1

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden AmariS1

@mehdiiwani

### CODE REVIEW

**Comment by mehdiiwani** [comment]
Hii

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel

**Comment by SamusElderg** [comment]
> How do i do that

Need to go to the Code4rena Discord server and check into the `i-want-to-be-a-warden` channel

**Comment by SamusElderg** [comment]
User still has not checked in, closing PR for now, will re-open when they check into the `i-want-to-be-a-warden` channel

**Review by SamusElderg — APPROVED** [review]

**Comment by SamusElderg** [comment]
Approved, but wont merge until confirmed maintenance period is completed

**Pull request merged**
