### PR TITLE
Add team SolidityScan

### PR DESCRIPTION
**Pull request by az0mb13**

### CODE REVIEW

**Review by itsmetechjay — APPROVED** [review]

**Comment by adamavenir** [comment]
@itsmetechjay do you know if they added the team members as wardens?

**Comment by itsmetechjay** [comment]
hey @adamavenir I saw both the names as json files in the data/handles folder. Did I do that right?

**Comment by adamavenir** [comment]
yeah, for sure. I just wanted to check cos I thought when I looked earlier they hadn't added the individuals yet, but I bet I just missed it.

**Comment by itsmetechjay** [comment]
Oh yeah that makes sense. Yay for tag-teaming!

**Pull request merged**
