### PR TITLE
Register warden codeninja819

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden codeninja819

@codeninja819

### CODE REVIEW

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Comment by codeninja819** [comment]
I have checked and sent request in the channel.

**Comment by codeninja819** [comment]
@sksb2180, Can you tell me why you closed this pr?

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

### Is this your Warden application?
You can help get your application approved by following these steps
**Check into the `i-want-to-be-a-warden` channel:**
- Please ensure you have checked into the `i-want-to-be-a-warden` channel in the Code4rena Discord server
image
- Please also make sure your *nickname* inside the C4 Discord server *exactly* matches your chosen C4 username
image
- Be aware we are referring to your *nickname*, not your main/global Discord username/handle
- If you do not remember the C4 username you chose, check the top of this PR where it says `Register warden .......... #1234` (see above example with the green rectangle around it)
- To change your nickname, go to the `i-want-to-be-a-warden` channel and *manually type* (do not copy paste) the `/nick` command and paste in your nickname or follow [this guide](https://support.discord.com/hc/en-us/articles/219070107-Server-Nicknames#h_01H4RRB3ZD1HD8R7YF2MKS4N16)

### Why is my PR closed?
- The Warden application PRs are closed after 2 days to keep the PR list clear and manageable 
- Don't worry though! We can re-open a PR at any time, a closed PR does not mean its deleted and you do *not* need to re-register, just follow the above steps and share this PR link in the `i-want-to-be-a-warden` channel so the contributors can re-open and get you into the wolfpack 🐺

**Review by Tendency001 — APPROVED** [review]

**Pull request merged**
