### PR TITLE
Register warden kal

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden kal

@tatlee69

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by Tatlee69** [comment]
Discord username : 3274.btc#2880
              id : 391318396102508544

**Comment by SamusElderg** [comment]
> 

You need to check into the `i-want-a-warden` channel please and make sure you set your local nickname in that discord server (not your global discord handle) to exactly `kal`
thanks

**Comment by Tatlee69** [comment]
Done thank you

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
