### PR TITLE
Register warden Quotebojo

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Quotebojo

@Monti-block

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by Monti-block** [comment]
[image: Screenshot 2023-02-27 at 08.37.38.png]

Hello,
Here is my discord. Let me know what do you need?
Thanks !
Regards

**Comment by SamusElderg** [comment]
> 

Need to make sure you check into the `i-want-to-be-a-warden` channel and also make sure you local nickname inside that server is set to exactly `Quotebojo` (not your global discord handle, just your nickname inside the C4 discord server/profile)

**Comment by Monti-block** [comment]
Hello,

[image: Screenshot 2023-02-28 at 08.22.50.png]
[image: Screenshot 2023-02-28 at 08.27.47.png]

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
