### PR TITLE
Register warden salah

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden salah

@Salah-SH

### CODE REVIEW

**Comment by SamusElderg** [comment]
The user might be `Salahpoly#8265` but has not yet checked into the `i-want-to-be-a-warden` channel anyway, will leave PR open for now

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by sksb2180** [comment]
Closing due to inactivity and warden still hasn't change his username.

**Comment by Salah-SH** [comment]
I have changed my username

**Comment by SamusElderg** [comment]
> Salah-SH

Ill check this now, but important to note your global Discord username/handle should exactly match what you put in the application (probably `SalahPoly`) and your Discord local nickname (your username specific to the Code4rena Discord server, not other Discord servers) should exactly match the Code4rena username you chose during the application (probably `Salah-SH`)

**Pull request closed without merging**
