### PR TITLE
Register warden henchman

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden henchman

@Etim-Paul

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Review by ETIM-PAUL — CHANGES_REQUESTED** [review]
actually name is "undefined" on discord. I joined the discord server.

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by sksb2180** [comment]
Closing due to inactive for 2 days.

**Pull request closed without merging**
