### PR TITLE
Register warden illshin

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden illshin

### CODE REVIEW

**Review by shinichirokinjo — APPROVED** [review]

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by shinichirokinjo** [comment]
Thanks for your comment, I would like to change my code4rena nickname to match the Discord, where do I start to respond?

**Comment by SamusElderg** [comment]
> o

I tagged you in the C4 discord with what you need to do 👍 if you have any issues see the pinned messages in the `i-want-to-be-a-warden` channel for more info on 'nicknames' in Discord

**Comment by shinichirokinjo** [comment]
Thank you! I was able to change my nickname to illshin. I would be happy if you could proceed with the authentication.

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
