### PR TITLE
Register warden peyodp

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden peyodp

@peyopeev

### CODE REVIEW

**Review by peyopeev — COMMENTED** [review]
review

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by peyopeev** [comment]
Hi, my Discord username is princo#6318.

Thanks.

На пт, 14.04.2023 г. в 7:20 ч. Samus ***@***.***> написа:

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Review by kartoonjoy — APPROVED** [review]

**Comment by peyopeev** [comment]
I've changed my discord name to *peyodp*, but I still can't login into my
account *peyodp*. Could you please have a look? Thanks!

На пт, 14.04.2023 г. в 23:10 ч. kartoonjoy ***@***.***>
написа:

**Pull request merged**
