### PR TITLE
Register warden sy413

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden sy413

@sohrubh

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by sohrubh** [comment]
My Discord ID: saurabh#9632

I mentioned it correctly while signing up.

**Comment by SamusElderg** [comment]
> 

Thanks, you need to check into the `i-want-to-be-a-warden` channel in the Code4rena Discord and make sure your nickname in that server (not your global discord handle) matches your chosen username: `sy413`

**Comment by sohrubh** [comment]
I have updated my nickname with my username.

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
