### PR TITLE
Register warden coderpanda

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden coderpanda

@krishna7860

### CODE REVIEW

**Review by krishna7860 — APPROVED** [review]

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by krishna7860** [comment]
> leave

Hi I have joined the discord could you please recheck

**Comment by SamusElderg** [comment]
> > leave
> 
> Hi I have joined the discord could you please recheck

I still cant see you in the discord, can you please let me know your discord handle and make sure you also check into the `i-want-to-be-a-warden` channel?

**Comment by krishna7860** [comment]
> 

Yes here is my discord handle Krishna Sharma#1534
I have checked in right now in i-want-to-be-a-warden channel with coderpanda username

**Pull request merged**
