### PR TITLE
Register warden ethicalhackerved

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden ethicalhackerved

@ethicalhackerved

### CODE REVIEW

**Comment by ethicalhackerved** [comment]
ok

**Review by ethicalhackerved — APPROVED** [review]

**Review by ethicalhackerved — COMMENTED** [review]
all good

**Review by ethicalhackerved — APPROVED** [review]

**Comment by ethicalhackerved** [comment]
approved !

**Review by ethicalhackerved — APPROVED** [review]
This is looking good.Lets get this merged :)

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
