### PR TITLE
Register warden Ankit1995

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Ankit1995

### CODE REVIEW

**Comment by 0xSorryNotSorry** [comment]
The user is not found on Discord

**Comment by agarwalankit3395** [comment]
> Auto-generated PR to register the new warden Ankit1995

This is my discord Id : HellBoy199533#6182

**Comment by 0xSorryNotSorry** [comment]
Waiting for the user to change the Discord handle for the warden name match.

**Comment by agarwalankit3395** [comment]
I have my discord handle to Ankit1995#6182

**Review by itsmetechjay — APPROVED** [review]

**Pull request merged**
