### PR TITLE
Register warden Serpentx

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Serpentx

### CODE REVIEW

**Review by hishammohamed101 — APPROVED** [review]

**Review by hishammohamed101 — COMMENTED** [review]
hi this is serpentx

**Review by hishammohamed101 — APPROVED** [review]
this is serpentx

**Review by hishammohamed101 — APPROVED** [review]

**Review by hishammohamed101 — COMMENTED** [review]
hisham4641 ,, 
⁠🐺i-want-to-be-a-warden

**Review by hishammohamed101 — CHANGES_REQUESTED** [review]
Serpent0x

**Comment by kartoonjoy** [comment]
Duplicate PR. Closing.

**Pull request closed without merging**
