### PR TITLE
Register warden ziyou-

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden ziyou-

### CODE REVIEW

**Comment by guimo3** [comment]
1

**Review by guimo3 — CHANGES_REQUESTED** [review]
This is looking great! I've left a few comments that should be addressed before this gets merged.

**Review by guimo3 — CHANGES_REQUESTED** [review]
This is looking great! I've left a few comments that should be addressed before this gets merged.

**Review by guimo3 — CHANGES_REQUESTED** [review]
This is looking great! I've left a few comments that should be addressed before this gets merged.

**Review by guimo3 — APPROVED** [review]

**Review by guimo3 — APPROVED** [review]
This is looking great! I've left a few comments that should be addressed before this gets merged.

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Comment by guimo3** [comment]
> 在 Discord 中找不到匹配的用户，暂时关闭此 PR
My name is  ziyou-  in Discord

**Pull request merged**
