### PR TITLE
Register warden roy7

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden roy7

@royvardhan

### CODE REVIEW

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Comment by royvardhan** [comment]
> Warden didn't checked out the channel `i-want-to-be-a-warden` yet.
> 
> 

image

Hi,Do I need to do anything else?

**Comment by sksb2180** [comment]
> > Warden didn't checked out the channel `i-want-to-be-a-warden` yet.
> 
> image
> 
> Hi,Do I need to do anything else?

please change your nickname to roy7

**Comment by royvardhan** [comment]
Done

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
