### PR TITLE
Register warden kendy

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden kendy

@luongtrongdai

### CODE REVIEW

**Review by luongtrongdai — APPROVED** [review]
Approve this PR

**Comment by SamusElderg** [comment]
> Approve this PR

Hi! Can you please confirm your nickname in the Code4rena Discord channel matches your application: `kendy` and also ensure you have checked into the `i-want-to-be-a-warden` channel in there

**Comment by luongtrongdai** [comment]
> Code4rena

Hello @SamusElderg, thank you for your reply. My discord account is dailuong#8962

**Comment by SamusElderg** [comment]
> > Code4rena
> 
> Hello @SamusElderg, thank you for your reply. My discord account is dailuong#8962

Thanks, i have contacted you in the warden channel, just need to change your nickname in there to match the application `kendy`, if you are not sure how to do this: https://support.discord.com/hc/en-us/articles/219070107-Server-Nicknames

Thanks!

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
