### PR TITLE
Register warden TepNik

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden TepNik

@TepNik

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by TepNik** [comment]
I_DoD_I#4460
@SamusElderg This is my tag

**Comment by SamusElderg** [comment]
> 

Thanks, can you please check into the `i-want-to-be-a-warden` channel of Discord and make sure you nickname is set in that Discord server to exactly `TepNik` thanks!

**Comment by TepNik** [comment]
@SamusElderg Done

**Comment by TepNik** [comment]
@SamusElderg 
Now my discord tag is TepNik#4460

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
