### PR TITLE
Register warden ghostmazew

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden ghostmazew

@ghostmaze

### CODE REVIEW

**Review by ghostmaze — COMMENTED** [review]
great!

**Review by ghostmaze — APPROVED** [review]
great

**Review by ghostmaze — APPROVED** [review]
great

**Comment by ghostmaze** [comment]
??

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Pull request closed without merging**
