### PR TITLE
Register warden pwnforce

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden pwnforce

@pwnforce

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by pwnforce** [comment]
my user in Discord is Majid#4308

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by pwnforce** [comment]
what do you mean "change their nicknam"?

**Comment by pwnforce** [comment]
where is the nickname that should be changed?

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
