### PR TITLE
Register warden ralph27

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden ralph27

@ralph27

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Comment by ralph27** [comment]
@SamusElderg Bac0n#8884 here it is

**Comment by SamusElderg** [comment]
> @SamusElderg Bac0n#8884 here it is

Hi, need to check into the `i-want-to-be-a-warden` channel and make sure your local nickname inside the Code4rena discord server (not your discord global handle) matches the c4 username you picked: `ralph27` 

Feel free to ping me here and/or in the `i-want-to-be-a-warden` when you have done so 👍

**Comment by ralph27** [comment]
@SamusElderg hey, can you check again please?

**Comment by SamusElderg** [comment]
> @SamusElderg hey, can you check again please?

Still need you to check into the `i-want-to-be-a-warden` channel, all else looks good 👍

**Pull request merged**
