### PR TITLE
Register warden mananabot

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden mananabot

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Comment by SamusElderg** [comment]
> I cannot join the Discord for some reason :/
> 
> image

I think Discord servers have been having issues today, have heard reports from others not being able to access Discord over the weekend. Might be better now, keep trying 👍

**Comment by itsmetechjay** [comment]
@mananabot sent you an email.

**Comment by itsmetechjay** [comment]
@mananabot sent you a follow up email. If you are still having issues, feel free to open a new help desk request.

**Pull request closed without merging**
