### PR TITLE
Register warden 0xjbadi_

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden 0xjbadi_

@0xjbadi

### CODE REVIEW

**Comment by 0xjbadi** [comment]
Please merge my PR :)

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by 0xjbadi** [comment]
Have Changed nickname for discord

**Comment by sksb2180** [comment]
Closed due to inactive after 2 days.

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
