### PR TITLE
Register warden olegthegoat

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden olegthegoat

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by olegmitrakhovich** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

"Oleg M #6640" is not showing up? that's what I put down in my application

**Comment by SamusElderg** [comment]
> > Can not find a matching user in Discord, will leave the application open for now though
> 
> "Oleg M #6640" is not showing up? that's what I put down in my application @SamusElderg 

It's a little confusing, but that's your Discord global handle/username. Whereas your local Discord nickname inside the Code4rena discord server needs to match your chosen C4 username :`olegthegoat`

If you can check into the `i-want-to-be-a-warden` channel with your local nickname set as exactly that we can continue 👍

**Comment by olegmitrakhovich** [comment]
> > > Can not find a matching user in Discord, will leave the application open for now though
> > 
> > 
> > "Oleg M #6640" is not showing up? that's what I put down in my application @SamusElderg
> 
> It's a little confusing, but that's your Discord global handle/username. Whereas your local Discord nickname inside the Code4rena discord server needs to match your chosen C4 username :`olegthegoat`
> 
> If you can check into the `i-want-to-be-a-warden` channel with your local nickname set as exactly that we can continue 👍

Sorry about that, I thought joining code4rena was enough. I checked into the "I-want-to-be-a-warden" channel and changed my nickname to: olegthegoat.

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
