### PR TITLE
Register warden 0x1e18

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden 0x1e18

@0x1e18

### CODE REVIEW

**Comment by 0x1e18** [comment]
Does this mean the registration was declined? @sksb2180

**Comment by 0x1e18** [comment]
@SamusElderg bump or answer please?

**Comment by SamusElderg** [comment]
> Does this mean the registration was declined? @sksb2180

Not declined, just not yet complete. Based on your username and info i have available, just need you to check into the `i-want-to-be-a-warden` channel in the Code4rena Discord and mention this PR by name: `0x1e18` and/or link: `https://github.com/code-423n4/code423n4.com/pull/10139` and then you will be advised of the next steps so this can be completed 👍 If you check into that channel asap i can handle it for you quickly!

**Comment by 0x1e18** [comment]
Just did that. Thanks!

**Comment by sksb2180** [comment]
> Does this mean the registration was declined? @sksb2180 

I'm sorry, I wasn't available and missed it later. Thanks a lot @SamusElderg for prompt reply. 🙏

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
