### PR TITLE
Register warden joshstevens19

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden joshstevens19

@https://github.com/joshstevens19

### CODE REVIEW

**Comment by joshstevens19** [comment]
👋🏾

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by joshstevens19** [comment]
WAGMI#4784 @SamusElderg

**Comment by joshstevens19** [comment]
0EC912BB-44B4-44A0-B055-8041EA6BF3F9
49FE4298-9584-490F-BF65-E0F14F15A6B5

**Comment by SamusElderg** [comment]
Have contacted user to get a png version of the avatar to replace the webp

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
