### PR TITLE
Register warden cats

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden cats

@0xcats

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by 0xcats** [comment]
Just changed my discord servername to 0xcats from cats to reflect that, sorry

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by 0xcats** [comment]
Ah I think you're correct, it's cats, just changed /nick in server

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
