### PR TITLE
Register bot sol2vuln

### PR DESCRIPTION
**Pull request by sockdrawermoney**
Registration for bot sol2vuln submitted by sock on behalf of NoamYakov and DavidGiladi.

Description:
sol2vuln is a bot designed to analyze Solidity smart contracts for potential vulnerabilities and gas optimizations.

It's based on slither, an open-source Solidity static analysis framework. It's written in Python and uses an AST-level static analysis technique to inspect the code for predefined security issues and optimization opportunities.

After analyzing the code, the bot aggregates the results and generates a detailed report, which is presented in a user-friendly and neatly formatted manner. 

This report includes a summary of the detected vulnerabilities and optimization suggestions, along with recommendations for how to address them.

### CODE REVIEW

**Comment by sockdrawermoney** [comment]
Hold off on merging this. accidentally included an unintended delete

**Comment by SamusElderg** [comment]
> Hold off on merging this. accidentally included an unintended delete

I can push a commit to fix the file deletion if you like just LMK 👍

**Comment by sockdrawermoney** [comment]
Thanks @SamusElderg -- yes please!

**Comment by SamusElderg** [comment]
> Thanks @SamusElderg -- yes please!

Okay, so slight issue here, im assuming this `Plasmablocks.json` (team handle) file deleted for you because you are likely on a windows computer (same as me) because there is already `plasmablocks.json` (warden handle) in that same folder (notice the lowercase `p`).

Whereas some filesystems (like linux) consider these two files different and let them co-exist due to case sensitivity, filesystems like windows' considers them to be the same/duplicate. 

We may need to temporarily patch this team handle back in (easiest way is probably to do a new PR rather than patching this one), and then maybe we need to log a GitHub issue to make sure when creating a team, the exact same warden name (`.toLowercase()` it to be sure) does not exist (and vice versa when a new Warden is created), *or* change the file structure so that team handles are placed in a different folder to warden handles.

Either way, id assume we also dont want it to be possible for something like this to exist for multiple different wardens:
- `WardenName.json`
- `wardenName.json`
- `wardenname.json`
- `WARDENNAME.json`
- `WARdenName.json`
- ... etc etc ...

So imo this definitely should be explored and prevented with some sanity checks

**Comment by SamusElderg** [comment]
i suspect if we update this to current branch it might rule out the issue now that file is already "deleted"

**Comment by SamusElderg** [comment]
yep that worked this PR now has no conflicts, ill close my other PR as this is now the same end-result, but will leave it for @CloudEllie && @sockdrawermoney to merge if needed still

**Review by CloudEllie — APPROVED** [review]

**Pull request merged**
