### PR TITLE
Register warden elvisvan

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden elvisvan

@elvisisvan

### CODE REVIEW

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Comment by elvisisvan** [comment]
> Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

i didn't know that so i was spam-logging in thinking it was a server's error lol, gotta wait now

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel, closing PR for now

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
