### PR TITLE
Register warden LuckyRadish

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden LuckyRadish

@LuckyRadish

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by LuckyRadish** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

Couldn't you find #spradish on Discord? I already joined to the server.

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by LuckyRadish** [comment]
> Have contacted user to change their nickname to match application

Just changed the nickanme to LuckyRadish. Thank you,

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
