### PR TITLE
Register warden BubblyOrca

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden BubblyOrca

@BubblyOrca

### CODE REVIEW

**Comment by itsmetechjay** [comment]
Registration incomplete - did not introduce self in Discord.

**Comment by BubblyOrca** [comment]
Done.

**Comment by BubblyOrca** [comment]
done

**Comment by itsmetechjay** [comment]
Did you pop in our C4 Discord? Your server nickname should match the registered handle @BubblyOrca

**Comment by BubblyOrca** [comment]
My server name is @saharasoundz#1513

**Comment by BubblyOrca** [comment]
Please let me know if this works out. My discord name is saharasoundz#1513

**Comment by itsmetechjay** [comment]
Asked you to send me a DM from our Discord. As I think it might be easier to communicate there.

**Comment by itsmetechjay** [comment]
In DM conversation with this user to see if we can get this warden registration handled.

**Review by itsmetechjay — APPROVED** [review]

**Comment by itsmetechjay** [comment]
Got it.  You are a mason.  If you are interested in becoming a warden,
please make a post in the #i-want-to-be-a-warden channel.  And update your
discord server nickname to match the BubblyOrca registration.

**Pull request merged**
