### PR TITLE
Style leaderboard  -- mobile

### PR DESCRIPTION
**Pull request by Simon-Busch**
- [x] Make table scrollable both horizontally and vertically
- [x] Freeze column header on desktop view
- [x] Freeze column header on mobile
- [x] Freeze first 2 columns on mobile
- [x] Reduce overall padding
- [x] remove the "TEAM" badge and bold the team name instead.
- [x] then shrink the team members to be 'pills' like the word "team" is and give them much smaller avatars, smaller text, and tight inline-block stacked pills under the team title.
- [x] reduce the avatar size
- [x] reduce overall padding, particularly vertical (which probably is helped by reducing avatar size)
- [x] reduce the L/R padding for ranking even more, possibly reduce size a little bit on the ranking numbers
- [x] Delete cosmos header
- [X] Add timeframe in header
- [x] Replace toggle for team with actual svg
- [x] new place for the select in the table head
- [x] reduce c4 logo size and center it
- [x] Let the purple line visible on scroll on mobile

### CODE REVIEW

**Comment by sockdrawermoney** [comment]
Nice work on this so far.

Screen Shot 2022-05-18 at 11 29 29 AM

Suggestion for all sizes:
- remove the "TEAM" badge and bold the team name instead.
- then shrink the team members to be 'pills' like the word "team" is and give them much smaller avatars, smaller text, and tight inline-block stacked pills under the team title. 

For mobile, I would say:
- reduce the avatar size
- reduce the padding for ranking even more, particularly vertical (which probably is helped by reducing avatar size)
- reduce overall padding and 
- keep the handles fixed, too when scrolling horizontally

Not sure about these but they occurred to me:
- bonus 1: add a very subtle drop-shadow under to kind of show the affordance of the scrollback. (remove the drop shadow when horiz scrolled to the far left)
- bonus 2: slight "fade out" (to page background color) on the right side of the scroll to show that there's more visible; remove the fade out when horiz scrolled to the far right.

I do understand that this looks "nicer" than the [fangraphs example](https://www.fangraphs.com/players/ty-france/17982/stats?position=1B) I linked to [in the previous discussion](https://github.com/code-423n4/code423n4.com/pull/1724#issuecomment-1118392650) (make sure to view the tables on mobile so you see how their horizontal scroll works). In my (strongly considered but not inflexible) opinion, we need to do a better job of optimizing stats for viewing stats, and having the data a little more dense in order to make screenshots more useful on mobile is essential. This is the chief comment I've heard on website usability.

@tealtigrrr feel free to chime in with a different or more nuanced opinion here. I'm really just wanting us to focus on the usefulness of the graph more than giving it so much room to breathe for pure aesthetic purposes, though I know every designer looks at the table and wants that. The reality though is that people aren't accessing the table on mobile for its aesthetics; they want to see data and—_very often_ they want to screenshot it. A more dense presentation makes that page more valuable on mobile and more likely to be shared, viewed, etc.

**Comment by Simon-Busch** [comment]
Hey @sockdrawermoney

thank you for the comments, very clear ! It is of course not finished, that was more to show builders the idea and have their opinion | feedback :-)

```
we need to do a better job of optimizing stats for viewing stats, and having the data a little more dense in order to make screenshots more useful on mobile is essential
```
Well noted

I'll carry on the work and have a talk with @tealtigrrr as well.

**Comment by sockdrawermoney** [comment]
Yeah no problem at all! I figured this was work in progress but wanted to leave a couple additional notes as you continue to revise. I dig the work so far!

**Comment by sockdrawermoney** [comment]
This is looking fantastic, @Simon-Busch

What if we hid the team members names and created a little triangle and icon next to the team name that allowed the user to toggle expand/collapse the team listing below when clicking the name?

image

**Comment by Simon-Busch** [comment]
Thank's @sockdrawermoney Great idea ! I'll work on it now :-)

**Comment by Simon-Busch** [comment]
I updated the style and place of the dropdown as per discussion with @tealtigrrr

**Comment by sockdrawermoney** [comment]
@tealtigrrr @Simon-Busch :100: :clap: 🎉 :clap: :clap: :clap: 👯‍♂️

**Review by sockdrawermoney — APPROVED** [review]

**Pull request merged**
