### PR TITLE
Register warden dsregtesrw43543

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden dsregtesrw43543

### CODE REVIEW

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by SamusElderg** [comment]
Have contacted user `regdergtsedrgter` with nickname `sdfgdsrgregte` to change their nickname to match application

**Comment by SamusElderg** [comment]
User has not yet responded, closing PR for now

**Pull request closed without merging**
