### PR TITLE
Register warden mayank0047

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden mayank0047

@codersharma2001

### CODE REVIEW

**Comment by codersharma2001** [comment]
Please complete the registration

**Review by codersharma2001 — APPROVED** [review]

**Review by codersharma2001 — APPROVED** [review]
Approved

**Review by codersharma2001 — COMMENTED** [review]
I wanna register

**Review by codersharma2001 — CHANGES_REQUESTED** [review]
Register me

**Review by codersharma2001 — COMMENTED** [review]
Done

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Review by codersharma2001 — APPROVED** [review]
pls accept

**Pull request closed without merging**
