### PR TITLE
Register warden kudarukuni

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden kudarukuni

@kudarukuni

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by kudarukuni** [comment]
im him

**Comment by SamusElderg** [comment]
> im him

You need to check into the `i-want-to-be-a-warden` channel in the code4rena discord server with your details matching your application, and your nickname in there must match you application `kudarukuni`

**Comment by kudarukuni** [comment]
i changed my nick to match the pr request whats next now

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
