### PR TITLE
Register warden rahul_meta

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden rahul_meta

@rahulEth

### CODE REVIEW

**Review by rahulEth — COMMENTED** [review]
https://www.linkedin.com/in/rahul-saini-87465b94/

**Comment by SamusElderg** [comment]
The user might be `rahulEth#4601` but has not yet checked into the `i-want-to-be-a-warden` channel so cant be sure, will leave this PR open for another day or so in case they check in

**Comment by SamusElderg** [comment]
User has not shown up in the `i-want-to-be-a-warden` channel with a matching nickname of `rahul_meta` so closing this PR for now

**Comment by rahul-crosstower** [comment]
hi @SamusElderg please let me  more about i-want-to-be-a-warden channel.

**Comment by rahulEth** [comment]
@SamusElderg what is i-want-to-be-a-warden?

**Pull request closed without merging**
