### PR TITLE
Register warden Derick

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Derick

@derickerickson3@outlook.com

### CODE REVIEW

**Comment by derick003** [comment]
@derick003

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Comment by derick003** [comment]
I just executed the corresponding command in the channel 'i-want-to-be-a-warden'.

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
