### PR TITLE
Register warden souilos

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden souilos

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by souilos** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

Here is my discord LouMa#8018

**Comment by SamusElderg** [comment]
> LouMa

You will need to check into the `i-want-to-be-a-warden` channel in the Code4rena Discord then we can continue. Thanks!

**Comment by SamusElderg** [comment]
Closing PR for now, will re-open after user checks into Discord

**Comment by souilos** [comment]
> > LouMa
> 
> You will need to check into the `i-want-to-be-a-warden` channel in the Code4rena Discord then we can continue. Thanks!

could you send me the link or an invitation to the channel please ?

**Comment by souilos** [comment]
> > > LouMa
> > 
> > 
> > You will need to check into the `i-want-to-be-a-warden` channel in the Code4rena Discord then we can continue. Thanks!
> 
> could you send me the link or an invitation to the channel please ?

All good my bad !

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
