### PR TITLE
Add warden pavan

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden pavan

 i had cleared Damn vul defi ctf
swc registry,
Hard knowlege in solidity,
erc20,
front end dev,
Bug hunter

### CODE REVIEW

**Comment by SamusElderg** [comment]
@sksb2180 looks like you have approved this, would you like me to update and merge or still confirming some details?

**Comment by sksb2180** [comment]
Handle diff, discord id is diff from submitted handle. Sent dm earlier, waiting for answer

**Comment by SamusElderg** [comment]
> Handle diff, discord id is diff from submitted handle. Sent dm earlier, waiting for answer

Whoops sorry! No probs

**Comment by sksb2180** [comment]
Closing this as a new pr is merged with corrected username

**Pull request closed without merging**
