### PR TITLE
Register warden karasu0888

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden karasu0888

@karasu0888

### CODE REVIEW

**Comment by Karasu0888** [comment]
First PR from code4rena.

**Review by Karasu0888 — APPROVED** [review]
First review for code4rena.

**Review by Karasu0888 — APPROVED** [review]
First review for code4rena.

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
