### PR TITLE
Register warden 0xAshura

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden 0xAshura

### CODE REVIEW

**Comment by Lord-Ravan** [comment]
warden/0xAshura

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by Lord-Ravan** [comment]
my discord is DemonX#6289

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application, closing PR for now, will re-open once details are correct

**Pull request closed without merging**
