### PR TITLE
Register warden piotrammain

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden piotrammain

@piotrammain

### CODE REVIEW

**Review by piotrammain — APPROVED** [review]

**Review by piotrammain — COMMENTED** [review]
ok

**Review by piotrammain — APPROVED** [review]
Approve

**Comment by itsmetechjay** [comment]
@piotrammain please join our Discord and introduce yourself in the #I-want-to-be-a-warden channel and we can finish processing your registration.

**Comment by SamusElderg** [comment]
The user has not yet checked into the #I-want-to-be-a-warden Discord channel, closing for now, can re-open if/after they check-in

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
