### PR TITLE
Register warden ro

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden ro

@https://github.com/rodrigoherrerai

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by rodrigoherrerai** [comment]
Hi @SamusElderg this is my discord name: rodrigoh#0623

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by rodrigoherrerai** [comment]
Hi @SamusElderg  I still don't have the registration. Let me know if you need anything else.

**Comment by SamusElderg** [comment]
> Hi @SamusElderg I still don't have the registration. Let me know if you need anything else.

image

**Comment by SamusElderg** [comment]
Have contacted user again to change their nickname to match application

**Comment by rodrigoherrerai** [comment]
Changed the username. Thank you very much for the help !

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
