### PR TITLE
Make findings.csv file available via community-resources URL

### PR DESCRIPTION
**Pull request by natevw**
The primary purpose of these changes is to address #8065, i.e. get the findings\.csv available as a public URL before we sooner-or-later remove it from the repo too like we've already done with contests data (xref #6203 / #7065).

However, the commits here do also tidy up a few TypeScript warnings missed during review of #7611 and #7922.

### CODE REVIEW

**Comment by natevw** [comment]
Whoops, missed one thing (the Netlify redirect) so converting this back to draft.

**Comment by natevw** [comment]
This is working for me now, you should be able to download a straight-up verbatim copy of findings\.csv via the new `/community-resources/findings.csv` URL, e.g. <https://deploy-preview-8247--code423n4-site.netlify.app/community-resources/findings.csv> for this deploy preview.

**Comment by sseefried** [comment]
I'm so happy to see this! So it will be available at https://code4rena.com/community-resources/findings.csv once the PR is merged?

**Comment by natevw** [comment]
> I'm so happy to see this! So it will be available at https://code4rena.com/community-resources/findings.csv once the PR is merged?

Yep, that's the plan anyway! Should be some release notes coming to keep an eye out for, but in short trying to help migrate this data more smoothly.

**Pull request merged**
