### PR TITLE
Register warden parseen254

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden parseen254

@parseen254

### CODE REVIEW

**Review by parseen254 — APPROVED** [review]
LGTM 🎉🥂

**Comment by sksb2180** [comment]
Asked the warden to change server name to match above.

**Comment by parseen254** [comment]
@sksb2180 Done

**Comment by sksb2180** [comment]
Cool

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
