### PR TITLE
Register warden invitedtea

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden invitedtea

### CODE REVIEW

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel, closing PR for now

**Comment by InvitedTea** [comment]
can this PR be open again, I just check in the i-want-to-be-a-warden channel,

**Review by InvitedTea — COMMENTED** [review]
Just check in the discord: i-want-to-be-a-warden channel,

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
