### PR TITLE
Register warden Defcon1

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Defcon1

@iamstanlee

### CODE REVIEW

**Comment by sksb2180** [comment]
Closed due to inactive after 2 days.

**Comment by Iamstanlee** [comment]
@sksb2180  What kind of activity is required?

**Comment by sksb2180** [comment]
Ping us in above mentioned channel on discord.

**Comment by Iamstanlee** [comment]
@sksb2180 https://discord.com/channels/810916927919620096/810957404887973929/1148118950790582415

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
