### PR TITLE
Register warden Beeback

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Beeback

@Bbek18

### CODE REVIEW

**Review by bbek18 — APPROVED** [review]
Welcome home!

**Review by bbek18 — APPROVED** [review]

**Review by bbek18 — CHANGES_REQUESTED** [review]
Ok im here

**Review by bbek18 — APPROVED** [review]

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Pull request closed without merging**
