### PR TITLE
Register warden RoRoNoa

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden RoRoNoa

@Jds-23

### CODE REVIEW

**Review by Jds-23 — APPROVED** [review]

**Comment by Jds-23** [comment]
:P

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by Jds-23** [comment]
0xjoydeeeep is the discord username

**Comment by sksb2180** [comment]
Closed due to inactive after 2 days.

**Pull request closed without merging**
