### PR TITLE
Register warden JAGADESH

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden JAGADESH

### CODE REVIEW

**Review by 0xrj — COMMENTED** [review]
perfect

**Review by 0xrj — COMMENTED** [review]
ready to go!

**Review by 0xrj — COMMENTED** [review]
how long

**Review by 0xrj — APPROVED** [review]
lol! messed up

**Comment by SamusElderg** [comment]
> how long

Hey @0xrj can you please change your Code4rena Discord nickname to match the application: `JAGADESH` thanks!

**Comment by 0xrj** [comment]
Done

**Comment by SamusElderg** [comment]
> Done

Thanks! ill reboot Discord to get a hard refresh then ill approve it!

**Review by SamusElderg — APPROVED** [review]

**Comment by 0xrj** [comment]
Thankyou ;)

**Pull request merged**
