### PR TITLE
Register warden muratctp

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden muratctp

@CeliktepeMurat

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by CeliktepeMurat** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

It should be Murat#8308 @SamusElderg

**Comment by SamusElderg** [comment]
> > Can not find a matching user in Discord, will leave the application open for now though
> 
> It should be Murat#8308 @SamusElderg

Thanks, can you set your nickname in the Code4rena Discord server to exactly `muratctp` and then please say hello/check into the `i-want-to-be-a-warden` channel? Thanks

**Comment by CeliktepeMurat** [comment]
@SamusElderg done.

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
