### PR TITLE
Register warden bibekhanal08

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden bibekhanal08

@bbek18

### CODE REVIEW

**Review by bbek18 — APPROVED** [review]

**Review by bbek18 — APPROVED** [review]
approved......

**Comment by bbek18** [comment]
Ok thanks..

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Comment by SamusElderg** [comment]
User has not checked into the discord channel, closing PR for now

**Pull request closed without merging**
