### PR TITLE
Register warden radakax

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden radakax

@DaniOrtegaB

### CODE REVIEW

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by DaniOrtegaB** [comment]
Hello! I changed the name just the same day, is it ok?

**Comment by DaniOrtegaB** [comment]
@sksb2180 @SamusElderg

**Review by SamusElderg — APPROVED** [review]

**Comment by DaniOrtegaB** [comment]
Thanks! What are the next steps?

**Pull request merged**
