### PR TITLE
Register warden benjioh5

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden benjioh5

@benjioh5

### CODE REVIEW

**Comment by benjioh5** [comment]
OMG

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by benjioh5** [comment]
benjioh5#3958

**Comment by SamusElderg** [comment]
> benjioh5#3958

Please check into the `i-want-to-be-a-warden` channel in Discord and mention this PR (`benjioh5`) thanks!

**Comment by benjioh5** [comment]
DONE!

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
