### PR TITLE
Register warden boringslav

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden boringslav

@boringslav

### CODE REVIEW

**Review by boringslav — APPROVED** [review]

**Review by boringslav — COMMENTED** [review]
Review

**Review by boringslav — APPROVED** [review]
Review

**Review by boringslav — APPROVED** [review]
Final

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
