### PR TITLE
Register warden PrincessTamara96

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden PrincessTamara96

@PrincessTamara

### CODE REVIEW

**Comment by PrincessTamara** [comment]
Thanks for letting me into @code423n4.com

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Comment by PrincessTamara** [comment]
My discord handle is princesscutire1#5121

**Comment by SamusElderg** [comment]
> My discord handle is princesscutire1#5121

Will need you to please check into the `i-want-to-be-a-warden` channel and mention this PR: `PrincessTamara96` or the link to it: `https://github.com/code-423n4/code423n4.com/pull/10610` thanks!

**Pull request closed without merging**
