### PR TITLE
Register warden BountyHunter

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden BountyHunter

@Openskyx

### CODE REVIEW

**Review by XMaxZone — COMMENTED** [review]
Why  registration failed

**Review by OpenSkyX — COMMENTED** [review]
Why registration failed

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Review by OpenSkyX — COMMENTED** [review]
My discord id is xmax3543. what to do now?

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Comment by OpenSkyX** [comment]
Already in i want to be warden channel

**Comment by OpenSkyX** [comment]
what do i need to do

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
