### PR TITLE
Register warden Bason

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Bason

### CODE REVIEW

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by SamusElderg** [comment]
User still has not replied, closing PR for now

**Comment by TeoLucidWork** [comment]
@SamusElderg , hi, sorry for not replying. Where did you contact me? On Email or discord? What should I change in order to for this PR to be merged? Thanks!

**Comment by SamusElderg** [comment]
> @SamusElderg , hi, sorry for not replying. Where did you contact me? On Email or discord? What should I change in order to for this PR to be merged? Thanks!

Contacted on discord! All good though, just need to set your local discord nickname (not your global discord handle) in the C4 discord server to exactly: `Bason` then send a message in the `i-want-to-be-a-warden` channel

Thanks!

**Comment by TeoLucidWork** [comment]
Hello,
I just changed it to Bason and sent a message in the i want to be a warden
channel

На пн, 6.02.2023 г. в 6:22 ч. samus ***@***.***> написа:

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
