### PR TITLE
Register warden 0xrichard_zheng

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden 0xrichard_zheng

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by richardzheng29** [comment]
Hey my discord account is richardzheng

**Comment by richardzheng29** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

richardzheng is existing user, Discord is now removing trailing four number.

**Comment by SamusElderg** [comment]
> Hey my discord account is richardzheng

Need you to joing the Code4rena Discord server and make sure to check into the `i-want-to-be-a-warden` channel too. Ideally mention this PR `0xrichard_zheng` at the same time to make it easier for contributors to match you to this PR

Thanks

**Comment by richardzheng29** [comment]
> Code4rena Discord server "https://discord.gg/code4rena"
says unable to accept invite"
What's wrong?

**Pull request closed without merging**
