### PR TITLE
Register warden kr3s

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden kr3s

### CODE REVIEW

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel, closing PR for now

**Comment by sksb2180** [comment]
Closed due to inactive after 2 days.

**Comment by itsmetechjay** [comment]
User has joined discord and reached out. Will proceed with processing registration.

**Review by itsmetechjay — APPROVED** [review]

**Pull request merged**
