### PR TITLE
Register warden Ragnar

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Ragnar

@knowashish

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by knowAshish** [comment]
knowashish#7421  THIS IS MY DISCORD

**Comment by SamusElderg** [comment]
> knowashish#7421 THIS IS MY DISCORD

Need you to check into the `i-want-to-be-a-warden` channel in the Code4rena discord and mention this pr: `Ragnar` so we can get this processed 👍

**Comment by knowAshish** [comment]
Okay, sure

**Comment by sksb2180** [comment]
Deleting branch as warden opened new pr with diff username. Approved

**Pull request closed without merging**
