### PR TITLE
Register warden dianpriyandani

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden dianpriyandani

@iyongkiws123

### CODE REVIEW

**Review by iyongkiws123 — COMMENTED** [review]
test

**Comment by SamusElderg** [comment]
> test

Hello @iyongkiws123 ! Could you please ensure you are in the Code4rena Discord server and your nickname in there matches your application: `dianpriyandani` ? Then we can proceed Thanks!

**Comment by SamusElderg** [comment]
Closing for now

**Comment by yongsxyz** [comment]
> Closing for now

Hii my username yongskiws

**Comment by SamusElderg** [comment]
> > Closing for now
> 
> Hii my username yongskiws

Thanks! Can you please change your nickname in the Code4rena Discord server to match you application? Should be: `dianpriyandani`

**Pull request closed without merging**
