### PR TITLE
Register warden sbh

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden sbh

### CODE REVIEW

**Comment by sbenhai** [comment]
?

**Review by sbenhai — APPROVED** [review]

**Review by sbenhai — COMMENTED** [review]
?

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by sbenhai** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

My Discord id is: sbh#7518

**Comment by SamusElderg** [comment]
> > Can not find a matching user in Discord, will leave the application open for now though
> 
> My Discord id is: sbh#7518

Need to check into the `i-want-to-be-a-warden` channel in the COde4rena Discord and then we can direct you to change any details to match the application so it can be processed 👍

**Comment by SamusElderg** [comment]
User still has not checked in, closing PR for now, will re-open once they check in

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
