### PR TITLE
Register warden chrisling-dev

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden chrisling-dev

@chrisling-dev

### CODE REVIEW

**Comment by sksb2180** [comment]
Have asked to change nickname to chrisling.

**Comment by chrisling-dev** [comment]
> Have asked to change nickname to chrisling.

Hey how do I change my nickname on C4? Can't sign in yet

**Comment by sksb2180** [comment]
I'm sorry, please change discord nickname for code4rena server as chrisling-dev. Thank you

Then someone can process the registration. Thank you

**Comment by chrisling-dev** [comment]
> I'm sorry, please change discord nickname for code4rena server as chrisling-dev. Thank you
> 
> Then someone can process the registration. Thank you

oh got it thanks, updated!

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
