### PR TITLE
Register warden krikolkk

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden krikolkk

@coreggon11

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Comment by coreggon11** [comment]
Hi @SamusElderg , discord username is kriko.eth

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
