### PR TITLE
Register warden EthereumCel

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden EthereumCel

@EthCel

### CODE REVIEW

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel

**Comment by SamusElderg** [comment]
User still has not checked in, closing PR for now

**Comment by EthCel** [comment]
> User still has not checked in, closing PR for now

I just checked in, sorry for the wait

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
