### PR TITLE
Register warden anugaavar

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden anugaavar

@gaavar

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by gaavar** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

Hello! I am here. My discord user is `anu#5867`
image

**Comment by SamusElderg** [comment]
> > Can not find a matching user in Discord, will leave the application open for now though
> 
> Hello! I am here. My discord user is `anu#5867` image

Thanks, can you please set your nickname to `anugaavar` in the code4rena discord server? It has to match your C4 username you picked (not your global discord handle/username; just your nickname in that server)

**Comment by sksb2180** [comment]
Closing stale PR

**Pull request closed without merging**
