### PR TITLE
1961 markdown math support

### PR DESCRIPTION
**Pull request by hannahtuttle**
Add math support to reports and to the preview component for submitting findings. 

Added dependencies:
rehype-katex
remark-math
gatsby-remark-mathjax-ssr

### CODE REVIEW

**Comment by Simon-Busch** [comment]
It seems it's working great @hannahtuttle  :-) Great job ! 

I see there are a lot of version update in yarn.lock, was is intentionnal or due to installing the new plugin ?

**Comment by hannahtuttle** [comment]
@Simon-Busch  thank you for reviewing this!  Also the yarn up dates were from installing new plugins.

**Comment by Simon-Busch** [comment]
@hannahtuttle Do we consider this PR as ok or still need to be re-worked after @joshuashort comment in the dev sync ?

**Comment by hannahtuttle** [comment]
@Simon-Busch  after looking into this the PR is good! @tealtigrrr before this gets merged, where is the best place to add documentation for these changes to the markdown files?

**Comment by tealtigrrr** [comment]
> @tealtigrrr before this gets merged, where is the best place to add documentation for these changes to the markdown files?

Do you mean so that our wardens, etc. know that they can include Math in their findings, etc.? I'm not sure exactly where that would live... possibly in our docs? Or we could make a note in the submission form (though we currently don't have language in our forms about markdown styling.)

**Comment by tealtigrrr** [comment]
Yeah @sockdrawermoney I think that suggestion is perfect, text included. @hannahtuttle does that work for you?

Would we want to note it anywhere in the docs as well for situations outside of submission forms? (maybe overkill?)

**Comment by sockdrawermoney** [comment]
No, I think that's sufficient

**Comment by hannahtuttle** [comment]
@Simon-Busch I have the links for the markdown on the submit finding form here. Can you look at these update?

**Review by Simon-Busch — APPROVED** [review]

**Comment by hannahtuttle** [comment]
Hey @captainmangoC4 , 
Can you take a look at this pull request? I just worked through the merge conflict after warden auth was merged into main. In TextArea.js the helptext had been removed, but the helptext was where I had added the markdown documentation links. So I left that in, but I wasn't sure if I should be removing the "Link to all referenced sections of code in GitHub." in fields.js as that is were the helptext is being set.

**Comment by hannahtuttle** [comment]
Currently working through merge conflicts after warden auth.

**Comment by tuttlehannah** [comment]
Hey @captainmangoC4,

I got those changes updated to get the markdown links fixed after the merge conflict was fixed. Can you just double check this, if it looks good to you then it is ready to merge!

**Review by captainmangoC4 — APPROVED** [review]
Looks good to me!

**Pull request merged**
