### PR TITLE
Register warden Breaking_ricky3

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Breaking_ricky3

@Nith567

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by Nith567** [comment]
Sorry i didn't notice, do i need to register again or will you my discord username: Nithin_3#7610

**Comment by SamusElderg** [comment]
> Sorry i didn't notice, do i need to register again or will you my discord username: Nithin_3#7610

Please make sure you check into the `i-want-to-be-a-warden` channel and mention this pr (`Breaking_ricky3`) and then we will be able to process it for you 👍

**Comment by SamusElderg** [comment]
Closing PR for now, if user wants to proceed with this one can re-open this PR and complete the merge once their nickname matches this application

**Pull request closed without merging**
