### PR TITLE
Register warden lyrxthegreat

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden lyrxthegreat

@lyrx

### CODE REVIEW

**Comment by lyrx** [comment]
Approve!

**Review by lyrx — APPROVED** [review]

**Review by lyrx — APPROVED** [review]

**Review by lyrx — APPROVED** [review]
Go.

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Comment by lyrx** [comment]
> Warden didn't checked out the channel i-want-to-be-a-warden yet.

Done

**Review by lyrx — APPROVED** [review]

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
