### PR TITLE
Register warden Jezus_

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Jezus_

@kaustubhthakur

### CODE REVIEW

**Comment by kaustubhthakur** [comment]
I am jezus

**Review by kaustubhthakur — COMMENTED** [review]
thats me

**Comment by SamusElderg** [comment]
Can not find a user with nickname: `Jezus_` in the Code4rena Discord, will leave the application open for now though

**Comment by kaustubhthakur** [comment]
username of my discord is DEadCodEr_00#8809

**Comment by SamusElderg** [comment]
> 

Thanks, you will need to set your nickname in the code4rena discord server (not your global handle/username; just the local nickname) to exactly: `Jezus_` then let us know when this is done so we can proceed

**Comment by kaustubhthakur** [comment]
Done sir :)

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
