### PR TITLE
Register warden DanialHamedi

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden DanialHamedi

@danialhamedi

### CODE REVIEW

**Review by danialhamedi — COMMENTED** [review]
done

**Review by danialhamedi — APPROVED** [review]

**Review by danialhamedi — APPROVED** [review]
approved

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Pull request closed without merging**
