### PR TITLE
Register warden dinesh1618

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden dinesh1618

### CODE REVIEW

**Comment by dineshpinto** [comment]
oops, missed the box to enter my github

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by dineshpinto** [comment]
joined the discord, updated nick and posted in `i-want-to-be-a-warden`

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
