### PR TITLE
Register warden mashharuki

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden mashharuki

@mashharuki

### CODE REVIEW

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel

**Comment by mashharuki** [comment]
I'm sorry. I saied "hi" in `i-want-to-be-a-warden` channel

**Comment by mashharuki** [comment]
https://discord.com/channels/810916927919620096/810957404887973929/1031078737283907664

**Review by SamusElderg — APPROVED** [review]

**Comment by mashharuki** [comment]
@SamusElderg Thank you very much!

**Pull request merged**
