### PR TITLE
Register warden berkayermis

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden berkayermis

@berkayermis

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by sksb2180** [comment]
Closing due to inactive for 2 days.

**Comment by berkayermis** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

currently berkayermis and also was Berkay Ermiş #2288 previously.

**Comment by SamusElderg** [comment]
> > Can not find a matching user in Discord, will leave the application open for now though
> 
> currently berkayermis and also was Berkay Ermiş #2288 previously.

Hi, could you please check into the `i-want-to-be-a-warden` channel in the Code4rena Discord server and mention this PR: `berkayermis` ? Then we can get everything sorted and get this merged

**Review by kartoonjoy — APPROVED** [review]

**Review by berkayermis — APPROVED** [review]

**Pull request merged**
