### PR TITLE
Register warden ONExEntry

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden ONExEntry

@MorganDPickens

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by MorganDPickens** [comment]
I’m in the discord I put a message in chat  NCADante

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by MorganDPickens** [comment]
Username changed brother

**Comment by MorganDPickens** [comment]
let me know if there is something else that you need

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
