### PR TITLE
Register warden RafilxTenfen

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden RafilxTenfen

@RafilxTenfen

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
:thinking:

**Comment by SamusElderg** [comment]
The user exists (Rafilx#7307) but has not yet checked into the `i-want-to-be-a-warden` channel with their nickname (not handle) set as `RafilxTenfen`

**Comment by RafilxTenfen** [comment]
> i-want-to-be-a-warden

Done!

**Comment by RafilxTenfen** [comment]
@sksb2180 Why close the PR ?

**Comment by SamusElderg** [comment]
> @sksb2180 Why close the PR ?

Thats standard practise when a PR is older than 2 days, dont worry though im having a look now and its very easy for me to re-open 👍

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
