### PR TITLE
Register warden Ethanolle

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Ethanolle

@ethanolle

### CODE REVIEW

**Review by ethanolle — COMMENTED** [review]
I love myself on this pr

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel

**Comment by SamusElderg** [comment]
> I love myself on this pr

@ethanolle its great you love yourself on this pr and all 😂 but we need you to check into the discord channel and say hello in the `i-want-to-be-a-warden` channel before we can continue. thanks

**Comment by ethanolle** [comment]
Done "Hello! This is me, ethanolle!"

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
