### PR TITLE
Register warden BY_DLIFE

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden BY_DLIFE

@LBiyou

### CODE REVIEW

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Comment by LBiyou** [comment]
so sorry, I was too busy before, can I continue now

**Review by sksb2180 — APPROVED** [review]

**Comment by LBiyou** [comment]
What do I need to do now?

**Comment by LBiyou** [comment]
I'm so sorry

**Pull request merged**
