### PR TITLE
Register warden dino0324

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden dino0324

### CODE REVIEW

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel

**Review by marcisaac — APPROVED** [review]

**Comment by marcisaac** [comment]
I want to be a warden

**Comment by sksb2180** [comment]
Closed due to inactive after 2 days.

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Pull request closed without merging**
