### PR TITLE
Register warden sosahacker

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden sosahacker

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by i-tsaturov** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

Found my old nickname with number-id. Here it is: turbo3000pew#4606

**Comment by SamusElderg** [comment]
> > Can not find a matching user in Discord, will leave the application open for now though
> 
> Found my old nickname with number-id. Here it is: turbo3000pew#4606

You will need to check into the `i-want-to-be-a-warden` channel in the Code4rena Discord and make sure your nickname in that server is set to match your chosen Code4rena username (if this is your PR then it needs to be `sosahacker`. Then we can proceed with getting this merged. Thanks

**Comment by SamusElderg** [comment]
> > You will need to check into the `i-want-to-be-a-warden` channel in the Code4rena Discord and make sure your nickname in that server is set to match your chosen Code4rena username (if this is your PR then it needs to be `sosahacker`. Then we can proceed with getting this merged. Thanks
> 
> hm, `sosahacker` is my username for code4rena, but for discord, I indicated that my nickname is `newdigit`

We are referring to your Discord 'nickname' (specifically inside the C4 Discord server) not your global Discord username/handle

**Comment by SamusElderg** [comment]
Closing PR for now, will re-open once user has changed nickname to match

**Comment by i-tsaturov** [comment]
Hi! I'm changed my nickname to sosahacker and I'm on your Discord channel right now!

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
