### PR TITLE
Register warden 0xjayz

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden 0xjayz

@0xjayzz

### CODE REVIEW

**Review by 0xjayzz — COMMENTED** [review]
Data is valid

**Review by 0xjayzz — APPROVED** [review]

**Review by 0xjayzz — APPROVED** [review]
IT is valid data

**Review by 0xjayzz — APPROVED** [review]

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Review by SamusElderg — APPROVED** [review]

**Comment by 0xjayzz** [comment]
i did check out # i-want-to-be-a-warden. @sksb2180 . This is the link
https://discord.com/channels/810916927919620096/810957404887973929/1160240359117443253
Please approve me.

**Pull request merged**
