### PR TITLE
Register warden Belarus95

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Belarus95

### CODE REVIEW

**Review by vladiflights — APPROVED** [review]
Hi

**Review by vladiflights — COMMENTED** [review]
#

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by SamusElderg** [comment]
Have not heard back from user in regard to setting Discord nickname to match, closing PR for now, can re-open if they reply and update

**Pull request closed without merging**
