### PR TITLE
Register warden dnkolegov

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden dnkolegov

@dnkolegov

### CODE REVIEW

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel

**Comment by dnkolegov** [comment]
Hi! I have checked into the channel!

**Comment by SamusElderg** [comment]
> Hi! I have checked into the channel!

Sorry, i checked again and still can not see you in the `i-want-t-be-a-warden` channel on the Code4rena Discord server, i can only search by your chosen C4 nickname (`dnkolegov`) so if it does not match that, can you let me know what your discord handle is? 

Ill close this PR for now as its older than 2 days, but dont worry, it will be re-opened when its ready to merge in!

Thanks!

**Comment by dnkolegov** [comment]
My handle is `alpha#4119`.

**Comment by dnkolegov** [comment]
Done!

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
