### PR TITLE
Register warden chikakayame

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden chikakayame

@Agusman14

### CODE REVIEW

**Comment by Agusman14** [comment]
Hmmm,

**Review by Agusman14 — APPROVED** [review]

**Comment by Agusman14** [comment]
Plss

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Pull request closed without merging**
