### PR TITLE
Register warden k6_monta

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden k6_monta

### CODE REVIEW

**Review by montak6 — CHANGES_REQUESTED** [review]
let s go gladiator

**Comment by montak6** [comment]
let s go gladiator

**Comment by SamusElderg** [comment]
The user might be `monta#8045` but has not yet checked into the `i-want-to-be-a-warden` channel anyway

**Comment by 0xSorryNotSorry** [comment]
Closing the PR as the application is overdue.

**Pull request closed without merging**
