### PR TITLE
Add register team in user dropdown

### PR DESCRIPTION
**Pull request by Simon-Busch**
- [x] Add an option in user dropdown to access register team
- [x] update css

### CODE REVIEW

**Comment by Simon-Busch** [comment]
Capture d’écran 2022-06-21 à 14 22 59

**Comment by Simon-Busch** [comment]
Capture d’écran 2022-06-21 à 14 22 59

**Comment by Simon-Busch** [comment]
> Let's put this on hold. If #2257 can be completed before warden auth is launched, we'll just keep the link to create a team there. Otherwise we will merge this until warden account page is done.

OK I put it on hold at the moment then

**Comment by captainmangoC4** [comment]
We can close this now that we have a link to team registration on the account page.

**Pull request closed without merging**
