### PR TITLE
Register warden Santa

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Santa

@firasbelhiba

### CODE REVIEW

**Review by firasbelhiba — COMMENTED** [review]
Hello, I'm Firas Belhiba  so called by Santa, a software engineer who likes to code stuff that people find useful. When I'm not busy hacking away at my keyboard, you can find me exploring new technologies, watching sci-fi movies, or trying to convince my dad to buy bitcoin. I have a passion for developing blockchain applications that disrupt industries, create innovative solutions , and, most importantly, make me look like a genius. As a blockchain engineer, I've been known to solve complex problems with blockchain technology, smart contracts, and DeFi, but I'm still trying to figure out how to explain blockchain to my mom. If you're looking for a highly skilled, motivated, and slightly nerdy software engineer, then look no further! Let's connect and make some blockchain magic happen.

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Comment by sksb2180** [comment]
Closed due to inactive after 2 days.

**Pull request closed without merging**
