### PR TITLE
Add warden ryanfu

### PR DESCRIPTION
**Pull request by code423n4**
This auto-generated PR registers the new warden ryanfu

### CODE REVIEW

**Comment by joshuashort** [comment]
currently `ryan.fu`, no announce

**Comment by itsmetechjay** [comment]
Sent ryan.fu a DM to see if we can get their server nickname updated.

**Comment by itsmetechjay** [comment]
Sent a nudge on 3/8.

**Comment by joshuashort** [comment]
After heroic effort, it's not (yet) to be.

**Pull request closed without merging**
