### PR TITLE
Register warden BOHDAN

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden BOHDAN

@@Biloonov

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Comment by Biloonov** [comment]
Recheck

ср, 7 черв. 2023 р. о 09:42 Samus ***@***.***> пише:

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by Biloonov** [comment]
Ok, thanks.

пт, 9 черв. 2023 р. о 05:29 Samus ***@***.***> пише:

**Pull request closed without merging**
