### PR TITLE
Register warden Ghost1462

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Ghost1462

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by enternaljohn** [comment]
Hmm! I have a question: my discord userid which i fill in register submittion is should be `[discord-username]#[id]` or `[discord-username]`. Because username on github not same with username on discord.

**Comment by enternaljohn** [comment]
image
I join to the server in the morning

**Comment by SamusElderg** [comment]
> 

We just need you to set your *Discord nickname* (not your Discord *username/handle) in teh Cod4rena Discord server to exactly: `Ghost1462` and check into the `i-want-to-be-a-warden` channel then we can process your application

**Comment by enternaljohn** [comment]
Oh! So i only have to change my nickname on discord channel code4rena and don't have to change the username on another channel right!

**Comment by enternaljohn** [comment]
image
Like this?

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
