### PR TITLE
Register warden quirky_pie

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden quirky_pie

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Comment by Streator** [comment]
Added to Discord user with a matching name. Please reopen PR

**Comment by SamusElderg** [comment]
> Added to Discord user with a matching name. Please reopen PR

Thanks, you will need to check into the `i-want-to-be-a-warden` channel and mention this PR (`quirky_pie`) 🙏

**Pull request closed without merging**
