### PR TITLE
Register warden HydroGypsy

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden HydroGypsy

@choco-cupcake

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by choco-cupcake** [comment]
Fixed the Discord step

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Comment by choco-cupcake** [comment]
Discord channel nick updated

**Review by sksb2180 — APPROVED** [review]

**Pull request merged**
