### PR TITLE
Register warden Weed0607

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Weed0607

### CODE REVIEW

**Comment by weed0607** [comment]
I want to be a warden!

**Review by weed0607 — COMMENTED** [review]
ok

**Review by weed0607 — APPROVED** [review]
I want to be a warden

**Review by weed0607 — CHANGES_REQUESTED** [review]
I approve all of this..

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
