### PR TITLE
Register warden D_Auditor

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden D_Auditor

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by Dliteofficial** [comment]
> Can not find a matching user in Discord, will leave the application open for now though

The username name is Dliteofficial but the discord given username is Dliteofficial#9758

**Comment by SamusElderg** [comment]
> > Can not find a matching user in Discord, will leave the application open for now though
> 
> The username name is Dliteofficial but the discord given username is Dliteofficial#9758

Thanks for reaching out, can you please change your nickname (not your handle, your 'nickname') in the Code4rena Discord server to `D_Auditor` and then check into the `i-want-to-be-a-warden` channel?

**Comment by Dliteofficial** [comment]
> > > Can not find a matching user in Discord, will leave the application open for now though
> > 
> > 
> > The username name is Dliteofficial but the discord given username is Dliteofficial#9758
> 
> Thanks for reaching out, can you please change your nickname (not your handle, your 'nickname') in the Code4rena Discord server to `D_Auditor` and then check into the `i-want-to-be-a-warden` channel?

Name change made and check in made also

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
