### PR TITLE
Improve automatic validation

### PR DESCRIPTION
**Pull request by dstaley**
This PR updates our validation script to check organizations, contests, and findings, and report missing/mismatched data.

### CODE REVIEW

**Comment by dstaley** [comment]
@adamavenir We have [duplicate contestids](https://github.com/code-423n4/code423n4.com/pull/36/checks?check_run_id=2615750768#step:5:8). How should we handle those?

**Comment by adamavenir** [comment]
@dstaley you are a lifesaver. Sheesh. Good catch.

**Comment by adamavenir** [comment]
Not the most fun answer here but I would say the ideal would be to:

1. change the ids to indeed be sequential
2. go back through and run the `awardCalc` script for each contest from `6` on 😬 
3. modify `findings.json`(manually) to include the correct data, including (a) fixing findings handles to match data, and (b) handling [this change](https://github.com/code-423n4/code423n4.com/commit/c560d87a4145aff208594f57b488d026c24edf4f) to split pocotiempo up into individual contributions

I want to again thank you for compensating so well for my detail deficiency!

**Comment by ninek9** [comment]
> Not the most fun answer here but I would say the ideal would be to:
> 
> 1. change the ids to indeed be sequential
> 2. go back through and run the `awardCalc` script for each contest from `6` on 😬
> 3. modify `findings.json`(manually) to include the correct data, including (a) fixing findings handles to match data, and (b) handling [this change](https://github.com/code-423n4/code423n4.com/commit/c560d87a4145aff208594f57b488d026c24edf4f) to split pocotiempo up into individual contributions
> 
> I want to again thank you for compensating so well for my detail deficiency!

Happy to help with this

**Pull request merged**
