### PR TITLE
Register warden Markair

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Markair

@markair77

### CODE REVIEW

**Review by markair77 — APPROVED** [review]

**Review by markair77 — APPROVED** [review]

**Comment by sksb2180** [comment]
Warden didn't checked out the channel `i-want-to-be-a-warden` yet.

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Comment by markair77** [comment]
Which discord user was attempted?

**Comment by SamusElderg** [comment]
> Which discord user was attempted?

If you can check into the `i-want-to-be-a-warden` channel and mention this PR (`Markair`) we can re-open this and get it merged 🙏

**Pull request closed without merging**
