### PR TITLE
Check userhandle refactor

### PR DESCRIPTION
**Pull request by eugenioclrc**
Fix to issue [2187](https://github.com/code-423n4/code423n4.com/issues/2187)

Plus a refactor to avoid duplicate isDangerous function.

### CODE REVIEW

**Review by captainmangoC4 — CHANGES_REQUESTED** [review]
Unfortunately netlify lambda functions don't make it this easy to share code across multiple functions. I've seen people in [netlify forums](https://answers.netlify.com/t/sharing-helper-function-between-lambdas/13934) suggesting to make utils into an npm package as a way around this. Another option is to call one lambda function from another with a HTTP request (you can see an example of this [here](https://github.com/code-423n4/code423n4.com/blob/feature/warden-auth/functions/submit-finding.js#L141))

Both of those options seem like overkill for a simple regex check. Maybe there is another option I haven't come across though.

**Comment by eugenioclrc** [comment]
I have remove the shared js and import the function on each endpoint, with a comment explaing why the function is repeated.

**Comment by captainmangoC4** [comment]
It looks like you made these changes to an out-of-date fork. The file `users.js` was replaced with `get-user.js`. I'm not sure what would be the best way to resolve the conflicts - I'm not a git expert. @eugenioclrc Is it alright with you if I just copy over the work into a fresh branch?

**Comment by eugenioclrc** [comment]
This pull request is not valid anymore.

**Comment by eugenioclrc** [comment]
Yikes! Agree, I will rollback or at least try to find a suitable solution

**Pull request closed without merging**
