### PR TITLE
Register warden zeroImpact

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden zeroImpact

@impactdot

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by impactdot** [comment]
My discord is Danny#6586. But if i need to change it, should i change it to zeroImpact?

**Comment by impactdot** [comment]
I replied in the github. But my discord is Danny#6586. Do i need to change it to zeroImpact?

**Comment by SamusElderg** [comment]
> I replied in the github. But my discord is Danny#6586. Do i need to change it to zeroImpact?
> On 6 Feb 2023 at 04:30 +0000, code-423n4/code423n4.com ***@***.***>, wrote:
> >
> > view it on GitHub
> 

No, your Discord global handle should be exactly the same as what you entered when you applied, it's your local Discord nickname only inside the C4 discord channel that you will need to set to `zeroImpact`

**Comment by SamusElderg** [comment]
> My discord global handle is Danny#6586 and I think this is the one I have stated during the registration. I have already joined the Code4rena discord. Is there anything else I should do?
> […](#)
> On 7 Feb 2023 at 00:32 +0000, samus ***@***.***>, wrote: > I replied in the github. But my discord is Danny#6586. Do i need to change it to zeroImpact? > On 6 Feb 2023 at 04:30 +0000, code-423n4/code423n4.com @.***>, wrote: > > view it on GitHub No, your Discord global handle should be exactly the same as what you entered when you applied, it's your local Discord nickname only inside the C4 discord channel that you will need to set to zeroImpact — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

You will need to check into the `i-want-to-be-a-warden` channel and make sure your local nickname inside the C4 Discord server is set to exactly `zeroImpact` to match the C4 username you picked. (not your global handle/username, thats probably correct to stay as `Danny#6586` if thats what you entered during application)

**Comment by impactdot** [comment]
I did change it now, thank you!

**Comment by SamusElderg** [comment]
> I did change it now, thank you!
> […](#)
> On 8 Feb 2023 at 02:55 +0000, samus ***@***.***>, wrote: > My discord global handle is Danny#6586 and I think this is the one I have stated during the registration. I have already joined the Code4rena discord. Is there anything else I should do? > … > On 7 Feb 2023 at 00:32 +0000, samus @.>, wrote: > I replied in the github. But my discord is Danny#6586. Do i need to change it to zeroImpact? > On 6 Feb 2023 at 04:30 +0000, code-423n4/code423n4.com @.>, wrote: > > view it on GitHub No, your Discord global handle should be exactly the same as what you entered when you applied, it's your local Discord nickname only inside the C4 discord channel that you will need to set to zeroImpact — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***> You will need to check into the i-want-to-be-a-warden channel and make sure your local nickname inside the C4 Discord server is set to exactly zeroImpact to match the C4 username you picked. (not your global handle/username, thats probably correct to stay as Danny#6586 if thats what you entered during application) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Thanks, we also need you to check into the `i-want-to-be-a-warden` channel

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
