### PR TITLE
Register warden itsencrypted

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden itsencrypted

@itsencrypted

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, closing this PR for now

**Comment by itsencrypted** [comment]
itsencrypted#6766 is my username in Discord.

**Comment by SamusElderg** [comment]
> itsencrypted

Need you to check into the `i-want-to-be-a-warden` channel in the Code4rena Discord channel before we can continue with the application. Thanks!

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
