### PR TITLE
Register warden nirban

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden nirban

@nirban256

### CODE REVIEW

**Comment by SamusElderg** [comment]
The user exists but has not yet checked into the `i-want-to-be-a-warden` channel

**Comment by SamusElderg** [comment]
User has not checked in, closing PR for now

**Comment by nirban256** [comment]
Hey @SamusElderg can I do the check in now?

**Comment by SamusElderg** [comment]
> Hey @SamusElderg can I do the check in now?

Yes absolutely, just need to check into the `i-want-to-be-a-warden` channel in the Code4rena Discord server. Feel free to ping me in there when you do so

**Comment by nirban256** [comment]
@SamusElderg  I have checked in by doing a message in the channel. My discord id is - Nirban#7083

**Review by SamusElderg — APPROVED** [review]

**Pull request merged**
