### PR TITLE
Register warden saintbay

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden saintbay

@devsaint-star

### CODE REVIEW

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by devsaint-star** [comment]
.saint_dev

**Comment by SamusElderg** [comment]
> .saint_dev

Please check into the `i-want-to-be-a-warden` discord channel and mention this PR: `saintbay ` and we can proceed from there 👍

**Comment by devsaint-star** [comment]
i just did that now, and i have change my Discord username to `saintauditor`  cos i think the . is confusing

**Comment by sksb2180** [comment]
Closed due to inactive after 2 days.

**Comment by SamusElderg** [comment]
Have contacted user to change their nickname to match application

**Pull request closed without merging**
