### PR TITLE
Register warden Strikeout

### PR DESCRIPTION
**Pull request by code423n4**
Auto-generated PR to register the new warden Strikeout

@mdulin2

### CODE REVIEW

**Review by mdulin2 — APPROVED** [review]
Handle and website link look good to me!

**Comment by SamusElderg** [comment]
Can not find a matching user in Discord, will leave the application open for now though

**Comment by mdulin2** [comment]
Gotcha. Didn't realize I needed to be in the Code4rena discord prior to the application going through. I'm in it now.

**Comment by SamusElderg** [comment]
> Gotcha. Didn't realize I needed to be in the Code4rena discord prior to the application going through. I'm in it now.

Thanks, what is your Discord username?

**Comment by mdulin2** [comment]
> 

Maxwell 'ꓘ' Dulin#7417, which was the same as the application. I assumed in joined the right Discord channel; the one at the bottom of the Code4rena page.

**Comment by mdulin2** [comment]
Any progress on this? I was hoping to participate soon.

**Comment by mdulin2** [comment]
Did I miss something here? @sksb2180 @SamusElderg

I don't know why this didn't get merged. I'm in the Discord and gave you all real information.

**Comment by mdulin2** [comment]
Tried re-registering and that didn't work since this username is now taken. Can you please approve this so that I can submit bugs? I like the username I had as well.

**Review by kartoonjoy — APPROVED** [review]

**Pull request merged**
